name: CI Workflow

on:
  push

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.dev.txt

      - name: Check lint
        run: |
          blue --check .; isort --check-only .

  build-python-package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.dev.txt

      - name: Build package
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-fox-package
          path: ./dist

